### ISSUE TITLE
simulate.exe GUI is rendered incorrectly all over the window

### ISSUE THREAD

**Issue by Juri-3D** [deepmind/mujoco#639]
Hey,
I had to switch to a new computer and while the simulations are running as always, I can't use the simulate.exe anymore. 
The GUI is rendered all over the place (see screenshot). The buttons are still clickable on the left black panel, although not visible.

The PC:
ASRock X670E Pro RS
AMD Ryzen 5 7600X (with integrated graphics)
32GB RAM
M.2 SSD
AMD Radeon RX 6800 XT
Windows 11 22H2 (22621.819)

I've tried the latest AMD Adrenalin (22.5.1 and 22.11.1) and PRO (22Q4) graphics driver versions.
I've tried different mujoco releases (2.3.0, 2.3.1) and built it from the source code, always with the same result.
Any help is appreciated.

<img width="1282" alt="Win11_mujoco_simulate" src="https://user-images.githubusercontent.com/120175472/206687580-bb7e574d-fb17-4c86-b99d-0bffb1a57420.png">

**Comment by saran-t** [comment]
Can you try disabling DPI scaling?

**Comment by Juri-3D** [comment]
> Can you try disabling DPI scaling?

I did, but nothing changed.
An addition to the specs above: I have two monitors, one with 1080p and one with 4k. But I already used those screens on the old PC.

**Comment by saran-t** [comment]
Hard for me to make suggestions without being able to reproduce the issue. Are you comfortable with C programming? I'd recommend writing a minimal application that just compiles a model, sets up a rendering context, renders an image, dumps to file, and see if you can get something sensible.

Alternatively, if you can install Python, you can transcribe our [tutorial Colab](https://github.com/deepmind/mujoco/blob/main/python/tutorial.ipynb) into a small Python script (specifically, just only as far as the first image rendered) and see if you can get the correct image.

**Comment by Juri-3D** [comment]
Sadly I'm a mechanical engineer with little experience in C or Python. 
The issue, however, seems not related to the simulation environment. I can open any example model or my complex models with the "basic.exe" and they are rendered and run perfectly fine. Only the clickable buttons/menus of the "simulate.exe" are broken.

**Comment by Ocanath** [comment]
I have the same issue. New laptop with AMD Ryzen 5 PRO 6650U with Radeon Graphics, and up to date drivers (Adrenalin Edition Version 22.11.2).

I used the prebuilt simulate.exe binary of mujoco release 2.3.2. 
I also built simulate.exe from source, same exact issue as the release version.

![image](https://user-images.githubusercontent.com/8154765/220223468-68f9cd7d-4010-44cd-9dbe-d527aa27500c.png)

I suspect this is an issue with AMD graphics specifically, since that seems to be the common element with me and @Juri-3D

**Comment by Leo428** [comment]
This is happening for me as well. My laptop has AMD CPU and GPU (Lenovo Z16). I remember simulate.exe worked in late 2022.

**Comment by saran-t** [comment]
@Leo428 Can I please ask you to please go through each [binary release version](https://github.com/deepmind/mujoco/releases) one-by-one to see when the error first occurred?

**Comment by Leo428** [comment]
@saran-t 
I tried as far back as version 2.1.2 and the problem persists on my laptop (Windows 11 and AMD chips). I also tested it on my windows 10 PC with an intel CPU and Nvidia GPU and version 2.3.2 worked fine.

Since I reinstalled my laptop's system in late 2022, I guess it's most likely a driver issue caused by either windows 11 or AMD updates.

**Comment by Ocanath** [comment]
Forgot to mention, I'm running windows 10

**Comment by Shavdrag** [comment]
I had the same issue, but it worked after adding simulate.exe of the mujoco folder in the NVIDIA Control Panel program settings and set the preferred graphics processor to the NVIDIA GPU. 
I think the program tried to use the integrated graphics of my laptop and somehow that caused a problem

**Comment by ArtifixPrime** [comment]
It seems to be a GPU driver issue. I also have a Radeon GPU and the issue resolved when I downgraded the driver. The version I'm currently using is Adrenalin 22.5.1

**Comment by rajuptvs** [comment]
I am also having a similar issue on amd based cpu, but haven't faced the issue on my other intel based cpu.

**Comment by saran-t** [comment]
I should've thought of this ages ago, but could people who are running into this problem please try setting the environment variables `MUJOCO_GL_DEBUG=1` and `LIBGL_DEBUG=verbose`, and see if you get any message?

**Comment by saran-t** [comment]
I just got hold of a Windows AMD machine for the first time today, and while I haven't been able to reproduce anything nearly as garbled as the screenshots posted in this thread, I can nevertheless see that the UI panels are not aligned correctly.

Can I please ask anyone affected who's still following this thread to verify:
- that the Simulate app is still garbled, and
- what happens when you press Tab and Shift+Tab to hide both UI panes

Thanks!

**Comment by NghiaPhamttk27** [comment]
The issue of the display being cut off still exists on my laptop. When I press Tab and Shift+Tab, the display returns to normal, but, of course, the user cannot interact with the UI panes. So, it is very likely that this issue is with the two interface panes. You can watch the video below.
[screen-capture (1).webm](https://github.com/google-deepmind/mujoco/assets/145578401/33576d3d-5263-45d5-a968-fdcaf55b5e1c)

**Comment by saran-t** [comment]
Could you please patch the following, launch the viewer (both with and without a model loaded), and post screenshots here? This patch replaces the side panels with solid blocks of colours, hopefully this will help us better understand what operation is causing the problem.

[0001-Set-debug-colors.patch](https://github.com/google-deepmind/mujoco/files/13060734/0001-Set-debug-colors.patch)

**Comment by NghiaPhamttk27** [comment]
I have tried both with a model and without a model. In the case with the model, even when I press Shift+Tab, I can't see the model as before. You can check the two videos below.
[With humanoid model.webm](https://github.com/google-deepmind/mujoco/assets/145578401/411a191a-0dba-49f7-953c-61833b5af03e)
[without model.webm](https://github.com/google-deepmind/mujoco/assets/145578401/67de0081-8e2a-436f-90c4-47dfeb3fa3cd)

**Comment by saran-t** [comment]
Thanks. Unfortunately that's not at all what I expected to see (not that I know what I expected to see, but certainly not that!).

This means that I _still_ can't repro this problem fully. Might take a while to get this figured out.

**Comment by NghiaPhamttk27** [comment]
Yeah, it's quite sad to hear. I still hope the issue can be resolved because I can't have an Nvidia GPU as a replacement anytime soon.

**Comment by Xiaxuli** [comment]
![image](https://github.com/google-deepmind/mujoco/assets/92970741/d72a72d0-9608-4244-97d0-92d1a11e5649)
help, why did I click simulate.exe and then the window flashed back

**Comment by saran-t** [comment]
Interestingly, the new bug report #1144 shows an identical screenshot to what I saw on last week. Note that it's much less garbled than what's posted here thus far, but still wrong.

**Comment by codeslord** [comment]
I have a laptop with AMD Internal GPU as well as Nvidia GPU running Windows 11. After recent AMD graphics driver update I faced the same issue. The way I fixed the issue is that, I went to Windows Settings->System->Display->Graphics and under Custom options for apps, clicked browse, chose the Simulate.exe. Once I have added the custom app, selected MuJoCo->Options and instead of let windows decide, chose my NVIDIA Graphics card as my Graphics Preference. Now it works fine.
<img width="523" alt="image" src="https://github.com/google-deepmind/mujoco/assets/4618356/c387144f-9322-489e-9159-4e0bea5819fa">

**Comment by Xiaxuli** [comment]
Thank you for your reply, but I tried your method, but it still did not solve the problem that the click could not open
![1699975017347](https://github.com/google-deepmind/mujoco/assets/92970741/3f53d319-aa1d-4058-a834-b2ee5e07b744)

**Comment by rkourdis** [comment]
@saran-t I have the exact same issue as the screenshot in #1144 with AMD driver `23.12.1` (on Ryzen 7 6800U). This is on a local build using VS 2022.

Interestingly enough, downgrading to `22.5.1` fixes the GUI and everything renders well (I remember trying a couple of different driver versions a while ago). That might give some hints as to what's going on.

**Comment by girishkolli** [comment]
I just started off with Mujoco and I faced the same problem. My CPU and GPU are both AMD. I believe is was on version 24.xx.xx.xx (forgot to check the exact number) and the GUI was glitching out. I downgraded my driver to 21.40.18.10 since it was already saved on my computer and now simulate.exe runs without any issues. I hope a fix can be found for the latest AMD drivers soon.

**Comment by RajneeshSingh111** [comment]
> Hey, I had to switch to a new computer and while the simulations are running as always, I can't use the simulate.exe anymore. The GUI is rendered all over the place (see screenshot). The buttons are still clickable on the left black panel, although not visible.
> 
> The PC: ASRock X670E Pro RS AMD Ryzen 5 7600X (with integrated graphics) 32GB RAM M.2 SSD AMD Radeon RX 6800 XT Windows 11 22H2 (22621.819)
> 
> I've tried the latest AMD Adrenalin (22.5.1 and 22.11.1) and PRO (22Q4) graphics driver versions. I've tried different mujoco releases (2.3.0, 2.3.1) and built it from the source code, always with the same result. Any help is appreciated.
> 
> <img alt="Win11_mujoco_simulate" width="1282" src="https://user-images.githubusercontent.com/120175472/206687580-bb7e574d-fb17-4c86-b99d-0bffb1a57420.png">

I faced the same issue with AMD Ryzen 6000 series and NVIDIA GEFORCE RTX GPU. I changed the GPU mode from standard to ultimate (in ASUS ROG zephyrus G15) and it fixed the issue as I shifted to NVIDIA GPU. I think there is any issue with the AMD driver.

**Comment by wjxway** [comment]
Can confirm this issue is still there for AMD stand-alone graphics card (7900XTX). Hopefully it can be fixed soon.

**Comment by moosewoler** [comment]
Same issue. Downgrade AMD driver to 21.12.1, then the problem was fixed.
My laptop works on AMD Ryzen 7 5700U with Radeon Graphics and Windows 11.

**Comment by vivek-kumar9696** [comment]
> I have a laptop with AMD Internal GPU as well as Nvidia GPU running Windows 11. After recent AMD graphics driver update I faced the same issue. The way I fixed the issue is that, I went to Windows Settings->System->Display->Graphics and under Custom options for apps, clicked browse, chose the Simulate.exe. Once I have added the custom app, selected MuJoCo->Options and instead of let windows decide, chose my NVIDIA Graphics card as my Graphics Preference. Now it works fine. <img alt="image" width="523" src="https://private-user-images.githubusercontent.com/4618356/282788751-c387144f-9322-489e-9159-4e0bea5819fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMzY2NzksIm5iZiI6MTczNjEzNjM3OSwicGF0aCI6Ii80NjE4MzU2LzI4Mjc4ODc1MS1jMzg3MTQ0Zi05MzIyLTQ4OWUtOTE1OS00ZTBiZWE1ODE5ZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDQwNjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA0MzBlZTYwZWZkYmZhYzkzMzNkYmFmNWM4NDI1ODBhYWNmOWUwYTFkNmE3NzYyNDA3OWE1ZDkwMzI2ZDY4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lZ4qv_NJxZNuBKqF8A7_laSzjxEI6Hl1__eOfzNbzHQ">

This worked perfectly for me. Thanks!!

**Comment by DIYman** [comment]
I can confirm that this issue still persists with Radeon RX 580, driver versions V24.9.1 and the previous release. The GUI is not functioning correctly—button clicks register inaccurately, as if there's an offset, causing unintended elements to be selected. Additionally, when a model is loaded, the GUI disappears entirely in simulate.exe.

**Comment by yuvaltassa** [comment]
As far as we can tell this has been fixed in recent versions of the AMD drivers. 
Can anyone confirm/deny that it is now solved?

**Comment by AQLK** [comment]
Unfortunately, the/some problem still persists for menus for recent AMD drivers. It is not garbled like the top image in this thread, but it now mostly black and gray. I have added an mp4 to this comment (see bottom) that shows what it looks like. The 3D visualization and the scrollbars respond as expected to the mouse input. 
In the movie I am clicking _a lot_ on the black/gray parts where the menu should be. At some point something happens (something expanded?) so that I can then drag the scrollbar up/down to make the whole menu pass by. Nonetheless, none of the buttons work as they should, they get triggered when clicking somewhere else (exactly like DIYman above me says).
The menu is visible when the executable is started without a model, but buttons also responds incorrectly then, with vertical click offset.

(Also, scrolling and dragging the scrollbar behaves like tablet swiping (this inverted w.r.t. standard behavior on Windows, but might be common on Mac?).)

**Libraries (x64, Windows):**
Mujoco: 3.3.5, glfw: 3.4. (Edit: screen dpi was at 100% from the moment of booting up the pc)

**Machine** (used AMD Adrenalin ensure latest driver for August 14):
<img width="616" height="779" alt="Image" src="https://github.com/user-attachments/assets/39f9a7ef-72fc-4ae8-bfaa-a6a128b4321d" />

https://github.com/user-attachments/assets/357af3a0-8315-4c8a-8f29-15a2183b92fa

**Comment by DIYman** [comment]
Sadly, problem still persists for me too.

> As far as we can tell this has been fixed in recent versions of the AMD drivers. Can anyone confirm/deny that it is now solved?

I have tested with the latest available version of AMD driver (25.8.1) as of today and Mujoco 3.3.5. UI still doesnt work.

https://github.com/user-attachments/assets/52518537-d326-4709-86a4-5c6898095511

**Comment by Diankes** [comment]
Same problem persist for me using a NVIDIA GeForce RTX 3050 Laptop GPU using windows 11, I tried changing windows Settings > Display > Graphics > Add a desktop app and adding the path to my binary either python.exe when using pip or the simulate.exe when using the release zip and changing the Gpu Preference to my GPU, same problem persisted after adding the binary path in NVIDIA Control Panel in Manage 3D Settings > Program Settings and adding the path to either python.exe or simulate.exe.

<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/be81908b-cd56-49a1-8cbd-6658852a7686" />

My env is
```plaintext
OS: Windows 11
GPU 1 (Integrated): AMD Radeon(TM) Graphics
  Driver: 31.0.12014.6 | Date: 7/11/2022 | WDDM 3.1
  VRAM: 495 MB | DirectX 12 Ultimate: Disabled

GPU 2 (Dedicated): NVIDIA GeForce RTX 3050 Laptop GPU
  Driver: 32.0.15.9186 | Date: 1/19/2026 | WDDM 3.2
  VRAM: 3962 MB | DirectX 12 Ultimate: Enabled
```

**Comment by harishfaqot** [comment]
I have same problem here using AMD Ryzen 8840HS with Radeon 780 iGPU. The problem solved by updating the firmware of the driver using latest version. My current working version 26.2.2.

This is the link for my processor for example : https://www.amd.com/en/support/downloads/previous-drivers.html/processors/ryzen/ryzen-8000-series/amd-ryzen-7-8840hs.html

**Comment by devshahofficial** [comment]
The recent driver datapoint is useful. It might help to collect a small compatibility matrix here: MuJoCo version, AMD GPU/iGPU, Adrenalin driver version, Windows build, DPI scaling, and whether `simulate` UI is fixed/offset/black panels. @harishfaqot reports 26.2.2 working on Radeon 780M; @AQLK and @DIYman previously saw failures on 3.3.5 with newer 25.x drivers. I can help summarize confirmed working vs failing combinations if a few people can add exact driver versions.

**Comment by jingkaimori** [comment]
I can confirm this issue is still reproducible on the latest MuJoCo release with a recent AMD driver.

**System Info**
- **OS**: Windows 10
- **GPU**: AMD Radeon(TM) Graphics ( integrated graphics, Device ID `0x1638` )
- **Driver Version**: `31.0.21912.2004` (released 2024-06-18)
- **MuJoCo Version**: 3.8.1 (Python package)

**Symptoms**
- Before loading any model, the Simulate GUI displays correctly (both left and right panels are visible).
- After loading an MJCF model, the **left and right UI panels turn completely black**. The buttons are still clickable but invisible.
- The **3D model viewport renders perfectly fine** at all times.

**What I have tried**
- Switched between GLFW and WGL backends via `MUJOCO_GL` — no effect.
- Disabled OpenGL rendering (`MUJOCO_GL=disable`) — not applicable for the interactive viewer.
- Updated MuJoCo to the latest `3.8.1` — issue persists.

**Screenshot**

<img width="1282" height="766" alt="Image" src="https://github.com/user-attachments/assets/52d96952-b47b-406e-9d16-0f7e6e0aef6e" />

<img width="1282" height="766" alt="Image" src="https://github.com/user-attachments/assets/c9b49ffe-52dc-4537-b74e-b860c8e62869" />
